#Store all your config's here.
#added to gitignore so will not be syned
shodan_api=""
bing_api=""
github_access_token=""
builtwith_api=""
censysio_id=""
censysio_secret=""
facebook_access_token = ""
google_cse_key= ""
google_cse_cx = ""
flickr_api=""
hashes_api=""
instagram_api=""
instagram_secret=""
ipinfodb_api=""
jigsaw_api=""
jigsaw_password=""
jigsaw_username=""
linkedin_api=""
linkedin_secret=""
twitter_consumer_key=""
twitter_consumer_secret=""
twitter_access_token = ""
twiter_access_token_secret = ""
zoomeyeuser = ""
zoomeyepass = ""
clearbit_apikey = ""
emailhunter=""
jsonwhois=""
fullcontact_api = ""
mailboxlayer_api = ""

virustotal_public_api = ""
