#Store all your config's here.
#added to gitignore so will not be syned

#Backup in ~/Desktop/config.py_backup

shodan_api=""
bing_api=""
github_access_token=""
builtwith_api=""
censysio_id=""
censysio_secret=""
facebook_access_token = ""
flickr_api=""
google_api=""
google_cse_key=""
google_cse_cx = ""
hashes_api=""
ipinfodb_api=""
jigsaw_api=""
jigsaw_password=""
jigsaw_username=""
linkedin_api=""
linkedin_secret=""
pwnedlist_api=""
pwnedlist_iv=""
pwnedlist_secret=""
reddit_id = ""
reddit_secret = ""
spyonweb_access_token = ""
twitter_consumer_key=""
twitter_consumer_secret=""
twitter_access_token = ""
twitter_access_token_secret = ""
zoomeyeuser = ""
zoomeyepass = ""
clearbit_apikey = ""
emailhunter=""
jsonwhois=""
instagram_token = ""
instagram_client_id = ""
instagram_client_secret = ""
fullcontact_api = ""
mailboxlayer_api = ""
virustotal_public_api =""
urlscanio_api = ""
